### PR TITLE
Lodash Deprecations + Yarn instead of Bower

### PR DESCRIPTION
**Pull request by BobNisco**
Sorry that there are 2 things in this PR, but looks like I merged the yarn PR into `working`, when it should have been `working-improvements`

- Use yarn instead of bower
- Utilize non-deprecated lodash method names

`yarn && yarn build && yarn test` work as expected

### CODE REVIEW

**Review by ghempton — APPROVED** [review]
What is the status of this? Might as well merge this in and then do another PR for lodash 4.

**Comment by BobNisco** [comment]
@ghempton This looks to be working. I pulled this locally, ran `yarn && yarn build && yarn test` and everything passed.

I was working on a lodash 3->4 upgrade in the monolith: https://github.com/getoutreach/outreach/compare/master...BobNisco:lodash but that will definitely need to be updated since it's ~2 months old

But, if you take the above work, use the new coalesce SHA hash from this repo after merging this PR, then we should be very close to lodash 3-> upgrade

**Comment by BobNisco** [comment]
Although, you may need to actually keep `_` on window in the monolith due to how Coalesce accesses `_`

**Comment by BobNisco** [comment]
I'm going to merge this and see how this works on the monolith side

**Pull request merged**
